name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Brent-Tunnicliff/action-setup-android@1.0.0-beta.1
      - name: Build
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Publish to local Maven
        run: ./gradlew publishToMavenLocal
      - name: Upload lib
        uses: actions/upload-artifact@v3
        with:
          name: Lib generated
          path: ~/.m2/repository